# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d2f21df3eed6747045331abed99ceb32ca591ec32ef9af88e82391f6d2431894330bce23ba0c2ef122b2e764a4a9cc582aff5c3aa070ef37037b4217e1ce0ec

test:
  secret_key_base: cdcf33c67c4c8b0718e8878948fba0560e90a6b4d72c72f1238b2ecfd1ffe914b003d35393ca56b795f2458fe30f5cafae78291d7483e36eedced3893a27e655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
